ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.AutomaticFrameAdvance = true
ENT.Model = "models/zerochain/props_bloodlab/zbl_maskbox.mdl"
ENT.Spawnable = true
ENT.AdminSpawnable = false
ENT.PrintName = "Respirator"
ENT.Category = "Zeros GenLab"
ENT.RenderGroup = RENDERGROUP_BOTH
