    --[[
        OS_UI -> Coded by ted.lua(https://steamcommunity.com/id/tedlua/)

        Please do not edit this file, it will revoke support rights from you.
    --]]


    if not CLIENT then return end

    function OS_UI.DrawRect( x, y, w, h, col )
        surface.SetDrawColor( col )
        surface.DrawRect( x, y, w, h )
    end

    function OS_UI.BuildFont( font, start, finish )
        for x = start, finish do
            surface.CreateFont( "OS_UI.Font." .. x, { font = font, size = x, weight = 0 } )
            surface.CreateFont( "OS_UI.Font.Bold." .. x, { font = font, size = x, weight = 700 } )
        end
    end

    OS_UI.BuildFont( "Roboto", 12, 120 )

    function OS_UI.DrawText( msg, fnt, x, y, c, align, extra )
        if extra then 
            draw.SimpleText( msg, fnt, x, y, c, align and align or TEXT_ALIGN_CENTER, TEXT_ALIGN_CENTER )
        else
            draw.SimpleText( msg, fnt, x, y, c, align and align or TEXT_ALIGN_CENTER )
        end
    end

    function OS_UI.DrawOutline( x, y, w, h, t, c )
    surface.SetDrawColor( c )
        for i = 0, t - 1 do
            surface.DrawOutlinedRect( x + i, y + i, w - i * 2, h - i * 2 )
        end
    end

    function OS_UI.DrawRoundedBox( rad, x, y, w, h, col )
        draw.RoundedBox( rad, x, y, w, h, col )
    end

    function OS_UI.DrawTexture( icon, x, y, w, h, col )
        surface.SetDrawColor( col )
        surface.SetMaterial( icon )
        surface.DrawTexturedRect( x, y, w, h )
    end

    function OS_UI.ConvertColour( tbl, reduction )
        reduction = reduction or 10
        return Color( tbl.r - reduction, tbl.g - reduction, tbl.b - reduction, tbl.a or 220 )
    end

    function OS_UI.CreateIconObject( self, icon, x, y, w, h, button, func, color )
        color = color or OS_UI.Colors.RED
        local image = vgui.Create( button and 'DImageButton' or 'DImage', self )
        image:SetSize( w, h )
        image:SetPos( x, y )
        image:SetMaterial( icon )
        --image:SetKeepAspect( true )
        if not button then return image end
        image.Paint = function( me, w, h ) 
            local hover = OS_UI.ConvertColour( color, 10 )
            me:SetColor( me:IsHovered() and hover or color ) 
        end
        image.DoClick = func
        return image
    end

    function OS_UI.CreateButton( parent, x, y, w, h, font, txt )
        local btn = vgui.Create( 'DButton', parent )
        btn:SetSize( w, h )
        btn:SetFont( font )
        btn:SetText( txt )
        btn:SetPos( x, y )
        btn:SetTextColor( Color( 255, 255, 255 ) )
        local hover_color = OS_UI.ConvertColour( OS_UI.Colors.BASE_HEADER, 3 )
        btn.Paint = function( me, w, h )
            OS_UI.DrawRoundedBox( 6, 0, 0, w, h, me:IsHovered() and hover_color or OS_UI.Colors.BASE_HEADER )
        end
        return btn
    end

    function OS_UI.DrawIcon( mat, x, y, col, w, h )
        surface.SetDrawColor( col and col or Color( 255, 255, 255 ) )
        surface.SetMaterial( mat )
        surface.DrawTexturedRect( x, y, w and w or 32, h and h or 32 )
    end

    function OS_UI.PaintBar( parent, base_color, switch_color, bar_color )
        if not parent.VBar then print( 'Nenhuma VBar encontrada.' ) return end
        parent.VBar.Paint = function( me, w, h ) if not base_color then return else OS_UI.DrawRect( 0, 0, w, h, base_color ) end end
        parent.VBar.btnUp.Paint = function( me, w, h ) if not switch_color then return else OS_UI.DrawRect( 0, 0, w, h, switch_color ) end end
        parent.VBar.btnDown.Paint = function( me, w, h ) if not switch_color then return else OS_UI.DrawRect( 0, 0, w, h, switch_color ) end end
        parent.VBar.btnGrip.Paint = function( me, w, h ) if not bar_color then return else OS_UI.DrawRect( 3, 0, w / 2, h, bar_color ) end end
    end

    local blue = Color( 97, 114, 160 )
    function OS_UI.CreateClickableRow( parent, main_panel_size, base_size, extra )
        local player_panel = vgui.Create( "DCollapsibleCategory", parent )
        player_panel:SetExpanded( 0 )
        player_panel:SetLabel( '' )
        player_panel:GetChildren()[ 1 ]:SetTall( base_size )
        
        local hidden_list = vgui.Create( 'DPanelList' )
        hidden_list:SetSpacing( 1 )
        player_panel:SetContents( hidden_list )

        local hidden_panel = vgui.Create( "DPanel" )
        hidden_panel:SetSize( hidden_list:GetWide(), extra )
        hidden_list:AddItem( hidden_panel )
        hidden_panel.Paint = function( me, w, h ) OS_UI.DrawRect( 0, 0, w, h, blue ) end
        return player_panel, hidden_panel
    end

    function OS_UI.SecondsToClock( seconds )
        local seconds = tonumber( seconds )
        if seconds <= 0 then
            return "00:00"
        else
            mins = string.format( "%02.f", math.floor( seconds / 60 ) )
            secs = string.format( "%02.f", math.floor( seconds - mins * 60 ) )
            return mins.. ":" .. secs
        end
    end